version: "3.7"

services:
  db:
    image: "postgres:11"
    container_name: "journaly_db"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=robin
      - POSTGRES_DB=journaly_db
      - POSTGRES_PASSWORD=password
    restart: always
  # backend:
  #   build:
  #     context: ./backend
  #     target: dev-node
  #   depends_on:
  #     - db
  #   ports:
  #     - '4000:4000'
  #   volumes:
  #     - ./backend:/usr/src/app:delegated
  #   networks:
  #     - backend
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run dev
  frontend:
    build:
      context: ./frontend
      target: dev-node
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app:delegated
    networks:
      - frontend
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  db:

networks:
  frontend:
  # backend:
